### ISSUE TITLE
Scripts work when users have configured pushd directory

### ISSUE THREAD

**Issue by etiennestuder** [gradle/gradle-enterprise-build-validation-scripts#236]
More details to be provided by @jprinet soon.

**Comment by jthurne** [comment]
So I understand how `cdpath` works and what it does, but I don't really understand how it changes the behavior of `pushd`.

**Comment by jthurne** [comment]
Another option for fixing this is to replace our use of `pushd` and `popd` with our own internal function that does the same thing `pushd` and `popd` do.

**Comment by jprinet** [comment]
It seems that the behavior [here](https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/bde92fa66e3ca7cb2f4beb639a3f633cfb7368ad/components/scripts/lib/maven.sh#L17) is impacted by `CDPATH` when using `pushd ""` (Note that this is mostly the case as `project_dir` is usually empty)

On the other hand, I could successfully run the scripts with CDPATH set without quote protection:
`pushd $project_dir` instead of `pushd "$project_dir"`

Here is a sequence of instructions demonstrating the issue:

```
bash-3.2$ export CDPATH="$HOME:$HOME/Desktop"
bash-3.2$ popd
bash: popd: directory stack empty
bash-3.2$ pushd
bash: pushd: no other directory
bash-3.2$ pwd
/Users/jeromep/Desktop/work/src/gradle-enterprise-build-validation-scripts/build/distributions/gradle-enterprise-maven-build-validation
bash-3.2$
bash-3.2$ popd
bash: popd: directory stack empty
bash-3.2$ pushd ""
/Users/jeromep
~ ~/Desktop/work/src/gradle-enterprise-build-validation-scripts/build/distributions/gradle-enterprise-maven-build-validation
bash-3.2$ pwd
/Users/jeromep
```

I let you confirm @jthurne if unprotecting the `$project_dir` is fine in such case. Another alternative could be to just unset `CDPATH` at the beginning of the script.

**Comment by jthurne** [comment]
> I let you confirm @jthurne if unprotecting the $project_dir is fine in such case.

That's risky. If the project_dir contains spaces, not using quotes around it will most likely lead to issues.

We could test for an empty project_dir before calling `pushd` and `popd`. That should also solve the problem but it would be a bit safer.
